image: centos:7

build:
  script: |
    ls
    pwd
    
    curl -o /tmp/go.tar.gz -L https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz
    cd /usr/local
    tar zxf /tmp/go.tar.gz
    export PATH=/usr/local/go/bin:$PATH
    go version
    go env
    cd ~

    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
    nvm use --lts

    ls
    pwd

    make dist
    cp dist/*.zip ${CI_PROJECT_DIR}

  artifacts:
    paths:
      - "*.zip"

