image: centos:7

build:
  script: |
    mkdir -p /go/src/github.com/crankykernel/cryptoxscanner
    cp -a . /go/src/github.com/crankykernel/cryptoxscanner
    
    curl -o /tmp/go.tar.gz -L https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz
    cd /usr/local
    tar zxf /tmp/go.tar.gz
    export PATH=/usr/local/go/bin:$PATH
    go version
    go env
    cd ~
    export GOPATH=/go

    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
    nvm use --lts

    cd /go/src/github.com/crankykernel/cryptoxscanner
    go get -u github.com/golang/dep/cmd/dep
    dep ensure
    go build
    (
      cd webapp
      npm install
      ./node_modules/.bin/ng build --prod --aot
    )

    # make dist
    # cp dist/*.zip ${CI_PROJECT_DIR}

  artifacts:
    paths:
      - "*.zip"

